/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Optionen.java
 *
 * Created on 19.04.2009, 17:22:58
 */

package at.ac.uibk.dps.wmsxgui.presentation;

import hu.kfki.grid.wmsx.Wmsx;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Rectangle;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import at.ac.uibk.dps.wmsxgui.business.BusinessManager;

/**
 *
 * @author WmsxGUI Team
 * @version 1.0
 */
public class Options extends javax.swing.JFrame {

    /**
     * 
     */
    private static final long serialVersionUID = 5689473181735526756L;
    private final BusinessManager businessman;
    private final Wmsx wmsx_service;

    /** Creates new form Optionen. */
    public Options() {
        this.businessman = BusinessManager.getInstance();
        this.wmsx_service = this.businessman.getWmsxService();

        this.initComponents();
        this.centerScreen();

        // Set icon
        final Image icon = (new ImageIcon(this.getClass()
                .getResource("/icon.png"))).getImage();
        this.setIconImage(icon);

    }

    /**
     * Positioniert das Fenster genau in der Mitte des Bildschirmes...
     * 
     */
    private void centerScreen() {
        final Dimension dim = this.getToolkit().getScreenSize();
        final Rectangle abounds = this.getBounds();
        this.setLocation((dim.width - abounds.width) / 2,
                         (dim.height - abounds.height) / 2);
        this.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.btn_close = new javax.swing.JButton();
        this.jLabel1 = new javax.swing.JLabel();
        this.tb_maxjobcount = new javax.swing.JTextField();
        this.jLabel2 = new javax.swing.JLabel();
        this.pf_afspassword = new javax.swing.JPasswordField();
        this.btn_forgetafspassword = new javax.swing.JButton();
        this.jLabel3 = new javax.swing.JLabel();
        this.pf_gridpassword = new javax.swing.JPasswordField();
        this.btn_forgetgridpassword = new javax.swing.JButton();
        this.btn_setafspassword = new javax.swing.JButton();
        this.btn_setgridpassword = new javax.swing.JButton();
        this.btn_setmaxjobcount = new javax.swing.JButton();

        this
                .setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        this.btn_close.setText("Close");
        this.btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                Options.this.btn_closeActionPerformed(evt);
            }
        });

        this.jLabel1.setText("Max JobCount");

        this.tb_maxjobcount.setText("5");

        this.jLabel2.setText("Afs Password");

        this.pf_afspassword.setText("jPasswordField1");

        this.btn_forgetafspassword.setText("forget");
        this.btn_forgetafspassword
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(
                            final java.awt.event.ActionEvent evt) {
                        Options.this.btn_forgetafspasswordActionPerformed(evt);
                    }
                });

        this.jLabel3.setText("Grid Password");

        this.pf_gridpassword.setText("jPasswordField1");

        this.btn_forgetgridpassword.setText("forget");
        this.btn_forgetgridpassword
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(
                            final java.awt.event.ActionEvent evt) {
                        Options.this.btn_forgetgridpasswordActionPerformed(evt);
                    }
                });

        this.btn_setafspassword.setText("set");
        this.btn_setafspassword
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(
                            final java.awt.event.ActionEvent evt) {
                        Options.this.btn_setafspasswordActionPerformed(evt);
                    }
                });

        this.btn_setgridpassword.setText("set");
        this.btn_setgridpassword
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(
                            final java.awt.event.ActionEvent evt) {
                        Options.this.btn_setgridpasswordActionPerformed(evt);
                    }
                });

        this.btn_setmaxjobcount.setText("set");
        this.btn_setmaxjobcount
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(
                            final java.awt.event.ActionEvent evt) {
                        Options.this.btn_setmaxjobcountActionPerformed(evt);
                    }
                });

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this
                .getContentPane());
        this.getContentPane().setLayout(layout);
        layout
                .setHorizontalGroup(layout
                        .createParallelGroup(
                                             javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                  layout
                                          .createSequentialGroup()
                                          .addGroup(
                                                    layout
                                                            .createParallelGroup(
                                                                                 javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(
                                                                      layout
                                                                              .createSequentialGroup()
                                                                              .addContainerGap()
                                                                              .addGroup(
                                                                                        layout
                                                                                                .createParallelGroup(
                                                                                                                     javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(
                                                                                                              this.jLabel3)
                                                                                                .addComponent(
                                                                                                              this.jLabel2)
                                                                                                .addComponent(
                                                                                                              this.jLabel1))
                                                                              .addPreferredGap(
                                                                                               javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                              .addGroup(
                                                                                        layout
                                                                                                .createParallelGroup(
                                                                                                                     javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(
                                                                                                          layout
                                                                                                                  .createSequentialGroup()
                                                                                                                  .addComponent(
                                                                                                                                this.tb_maxjobcount,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                52,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                  .addPreferredGap(
                                                                                                                                   javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                  .addComponent(
                                                                                                                                this.btn_setmaxjobcount))
                                                                                                .addGroup(
                                                                                                          javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                          layout
                                                                                                                  .createSequentialGroup()
                                                                                                                  .addGroup(
                                                                                                                            layout
                                                                                                                                    .createParallelGroup(
                                                                                                                                                         javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                    .addComponent(
                                                                                                                                                  this.pf_gridpassword,
                                                                                                                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                  214,
                                                                                                                                                  Short.MAX_VALUE)
                                                                                                                                    .addComponent(
                                                                                                                                                  this.pf_afspassword,
                                                                                                                                                  javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                  214,
                                                                                                                                                  Short.MAX_VALUE))
                                                                                                                  .addPreferredGap(
                                                                                                                                   javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                  .addGroup(
                                                                                                                            layout
                                                                                                                                    .createParallelGroup(
                                                                                                                                                         javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                    .addComponent(
                                                                                                                                                  this.btn_setafspassword)
                                                                                                                                    .addComponent(
                                                                                                                                                  this.btn_setgridpassword))
                                                                                                                  .addPreferredGap(
                                                                                                                                   javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                  .addGroup(
                                                                                                                            layout
                                                                                                                                    .createParallelGroup(
                                                                                                                                                         javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                    .addComponent(
                                                                                                                                                  this.btn_forgetgridpassword,
                                                                                                                                                  javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                    .addComponent(
                                                                                                                                                  this.btn_forgetafspassword,
                                                                                                                                                  javax.swing.GroupLayout.Alignment.TRAILING)))))
                                                            .addGroup(
                                                                      layout
                                                                              .createSequentialGroup()
                                                                              .addGap(
                                                                                      192,
                                                                                      192,
                                                                                      192)
                                                                              .addComponent(
                                                                                            this.btn_close,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                            84,
                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE)))
                                          .addContainerGap()));
        layout
                .setVerticalGroup(layout
                        .createParallelGroup(
                                             javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                  layout
                                          .createSequentialGroup()
                                          .addContainerGap()
                                          .addGroup(
                                                    layout
                                                            .createParallelGroup(
                                                                                 javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(
                                                                          this.jLabel1)
                                                            .addComponent(
                                                                          this.tb_maxjobcount,
                                                                          javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                          javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(
                                                                          this.btn_setmaxjobcount))
                                          .addPreferredGap(
                                                           javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addGroup(
                                                    layout
                                                            .createParallelGroup(
                                                                                 javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(
                                                                          this.jLabel2)
                                                            .addComponent(
                                                                          this.pf_afspassword,
                                                                          javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                          javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(
                                                                          this.btn_forgetafspassword)
                                                            .addComponent(
                                                                          this.btn_setafspassword))
                                          .addPreferredGap(
                                                           javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addGroup(
                                                    layout
                                                            .createParallelGroup(
                                                                                 javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(
                                                                          this.jLabel3)
                                                            .addComponent(
                                                                          this.pf_gridpassword,
                                                                          javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                          javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(
                                                                          this.btn_forgetgridpassword)
                                                            .addComponent(
                                                                          this.btn_setgridpassword))
                                          .addGap(18, 18, 18)
                                          .addComponent(this.btn_close)
                                          .addContainerGap(
                                                           javax.swing.GroupLayout.DEFAULT_SIZE,
                                                           Short.MAX_VALUE)));

        this.pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_setafspasswordActionPerformed(
            final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_setafspasswordActionPerformed
        this.wmsx_service.rememberAfs(new String(this.pf_afspassword
                .getPassword()));
        System.out.println(new String(this.pf_afspassword.getPassword()));
    }// GEN-LAST:event_btn_setafspasswordActionPerformed

    private void btn_setgridpasswordActionPerformed(
            final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_setgridpasswordActionPerformed
        this.wmsx_service.rememberGrid(new String(this.pf_gridpassword
                .getPassword())); // fehler??
        System.out.println(new String(this.pf_gridpassword.getPassword()));
    }// GEN-LAST:event_btn_setgridpasswordActionPerformed

    private void btn_forgetafspasswordActionPerformed(
            final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_forgetafspasswordActionPerformed

        this.wmsx_service.forgetAfs();
    }// GEN-LAST:event_btn_forgetafspasswordActionPerformed

    private void btn_forgetgridpasswordActionPerformed(
            final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_forgetgridpasswordActionPerformed

        // die funktion gibts nicht :-(
    }// GEN-LAST:event_btn_forgetgridpasswordActionPerformed

    private void btn_setmaxjobcountActionPerformed(
            final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_setmaxjobcountActionPerformed
        try {
            final int maxjobcnt = Integer.parseInt(this.tb_maxjobcount
                    .getText());

            if (maxjobcnt > 0) {

                this.wmsx_service.setMaxJobs(maxjobcnt);

            } else {
                JOptionPane
                        .showMessageDialog(
                                           this,
                                           "MaxJobCount has to be greater than zero!",
                                           "WMSX GUI - Options",
                                           JOptionPane.ERROR_MESSAGE);
            }

        } catch (final NumberFormatException e) {
            JOptionPane
                    .showMessageDialog(this,
                                       "MaxJobCount isn't an valid Integer!",
                                       "WMSX GUI - Options",
                                       JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btn_setmaxjobcountActionPerformed

    private void btn_closeActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_closeActionPerformed
        this.setVisible(false);
    }// GEN-LAST:event_btn_closeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_forgetafspassword;
    private javax.swing.JButton btn_forgetgridpassword;
    private javax.swing.JButton btn_setafspassword;
    private javax.swing.JButton btn_setgridpassword;
    private javax.swing.JButton btn_setmaxjobcount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pf_afspassword;
    private javax.swing.JPasswordField pf_gridpassword;
    private javax.swing.JTextField tb_maxjobcount;
    // End of variables declaration//GEN-END:variables
}
